### ISSUE TITLE
generator.py

### ISSUE THREAD

**Issue by batrlatom** [jario-jin/yolov5-on-nvidia-jetson#1]
Hi, I am trying to evaluate your code for export competition. I was trying your code, but I am unable to find a file named generator.py.  Would you please add it so I can evaluate your code correctly? Thanks

**Comment by jario-jin** [comment]
Hi
It's already here: "yolov5-on-nvidia-jetson/yolov5/generator.py"
You need to enter the directory yolov5:

```
cd yolov5
python3 generator.py ../models/yolov5s.pt
```

**Comment by batrlatom** [comment]
got it, thank you
